//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeeShift1
    {
        public int ID { get; set; }
        public int employee_id { get; set; }
        public int shift1_id { get; set; }
    }
}
