//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class factoryDBEntities : DbContext
    {
        public factoryDBEntities()
            : base("name=factoryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<department1> department1 { get; set; }
        public virtual DbSet<employeeShift1> employeeShift1 { get; set; }
        public virtual DbSet<shift1> shift1 { get; set; }
        public virtual DbSet<user_actions> user_actions { get; set; }
    }
}
